### ISSUE TITLE
Texture2D

### ISSUE THREAD

**Issue by herve-ch** [EiTaNBaRiBoA/JsonClassConverter#3]
Hello I try to serialize a resource with a Texture2D but it doesn't work, we can't use Texture2D?

**Comment by EiTaNBaRiBoA** [comment]
> Hello I try to serialize a resource with a Texture2D but it doesn't work, we can't use Texture2D?

Hello, i will take a look at it, thanks for testing

**Comment by herve-ch** [comment]
Hello there! in my case I was trying to store a player inventory, each slot has an item with a texture2D resource so I expect to get my textures back when getting my class from my stored ison file.

Can I ask another question? I tried to serialize deserialize a Godot dictionary with custom classes but when I get my class back, I got a dictionary of dictionary. Are dictionaries supported ?  Thanks for your work

**Comment by EiTaNBaRiBoA** [comment]
> Hello there! in my case I was trying to store a player inventory, each slot has an item with a texture2D resource so I expect to get my textures back when getting my class from my stored ison file.
> 
> Can I ask another question? I tried to serialize deserialize a Godot dictionary with custom classes but when I get my class back, I got a dictionary of dictionary. Are dictionaries supported ? Thanks for your work

Yes, dictionaries are supported, although currently without typed or referenced values. I'm looking forward to Godot 4.4, which will introduce typed dictionaries. Once that's released, I'll add compatibility to ensure the plugin works smoothly with the new features. For the time being, only basic dictionaries are supported, but rest assured that support for reference types and objects is on the roadmap and will be included in a future update.

For now I will start working on texture2d and other resource types

**Comment by herve-ch** [comment]
ok thanks, for now I'll just use Arrarys instead of dictionaries and String path instead of Texture2D, then get the texture2D back from the String

**Comment by EiTaNBaRiBoA** [comment]
> ok thanks, for now I'll just use Arrays of Class instead of dictionaries and String path instead of Texture2D, then get the texture2D back from the String

The Texture2D issue is fixed.  Please let me know when Godot 4.4 is released so i can update the typed dictionaries.

**Comment by herve-ch** [comment]
Godot 4.4 dev 2 is released and support typed dictionaries

**Comment by EiTaNBaRiBoA** [comment]
> Godot 4.4 dev 2 is released and support typed dictionaries

I'm hesitant to make changes until Godot 4.4 reaches at least beta stage, as I'd like to avoid breaking compatibility with Godot 4.3 as this plugin was released specifically to godot 4.3. Once the beta is released, it signals that the full release is close, and transitioning users to 4.4 will be smoother.

**Comment by herve-ch** [comment]
yes no worries we can wait for final release no rush

Thanks
