### ISSUE TITLE
Question on serialising classes

### ISSUE THREAD

**Issue by MatthewHinds** [EiTaNBaRiBoA/JsonClassConverter#4]
Hi there. I noticed your documentation mentioning you need to annotate properties with @export. How would you achieve the following as Godot does not allow classes to be exported.

Example code:
```
class_name PlayerData
@export var inventory : Inventory
@export var skills : Skills
```

I'm currently using my own implementation of a JSON serialiser and stumbled upon your repo here. So I'm wondering if the above is possible. Thanks

**Comment by EiTaNBaRiBoA** [comment]
> Hi there. I noticed your documentation mentioning you need to annotate properties with @export. How would you achieve the following as Godot does not allow classes to be exported.
> 
> Example code:
> 
> ```
> class_name PlayerData
> @export var inventory : Inventory
> @export var skills : Skills
> ```
> 
> I'm currently using my own implementation of a JSON serialiser and stumbled upon your repo here. So I'm wondering if the above is possible. Thanks

Yes, it does. The latest commit adds support for nested resources, along with existing support for multi-nested objects.
