### ISSUE TITLE
Error with new commits

### ISSUE THREAD

**Issue by herve-ch** [EiTaNBaRiBoA/JsonClassConverter#6]
Hello, since the new commits there is an error when I create resources inside .tres file (embedded resource)
I can't use json to class anymore

It did work with previous version

See my example mini project:
[test-serialize-json-2.zip](https://github.com/user-attachments/files/16973557/test-serialize-json-2.zip)

Thanks

**Comment by EiTaNBaRiBoA** [comment]
> Hello, since the new commits there is an error when I create resources inside .tres file (embedded resource) I can't use json to class anymore
> 
> It did work with previous version
> 
> See my example mini project: [test-serialize-json-2.zip](https://github.com/user-attachments/files/16973557/test-serialize-json-2.zip)
> 
> Thanks

Hi, I have updated the [Code](https://github.com/EiTaNBaRiBoA/JsonClassConverter/blob/main/addons/JsonClassConverter/JsonClassConverter.gd) try to give it a shot and see if it works. The issue was that FileAccess.exists checks for a normal paths while the SAVE loaded sub-resource.

**Comment by herve-ch** [comment]
It works with the test project but I still got an error in my project

<img width="1016" alt="Capture d’écran 2024-09-11 à 19 25 32" src="https://github.com/user-attachments/assets/18424d3b-bf27-4692-9b98-461d87065034">

**Comment by EiTaNBaRiBoA** [comment]
Add me to discord shogidoubled#2008 i want to see what is happenning

**Comment by herve-ch** [comment]
it tells me username does not exists

**Comment by EiTaNBaRiBoA** [comment]
> it tells me username does not exists

can you give me yours i will add you

**Comment by herve-ch** [comment]
Kyo#2086

**Comment by EiTaNBaRiBoA** [comment]
Fixed
